---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
- name: source
- name: version

outputs:
  - name: dist

caches:
  - path: .gradle
  - path: source/dependency-check-cache

run:
  path: source/pipeline/scripts/build.sh
