boclips:
  lti:
    initiateLoginUrl: 'https://lti.staging-boclips.com/v1p3/initiate-login'
    issuerUrl: "https://lti-demo.staging-boclips.com"
    targetLinkUri: "https://lti.staging-boclips.com/collections"
    privateSigningKey:
    publicSigningKey:
  authentication:
    endPoint: "https://login.staging-boclips.com/auth"
