boclips:
  lti:
    initiateLoginUrl: 'https://lti.boclips.com/v1p3/initiate-login'
    issuerUrl: "https://lti-demo.boclips.com"
    privateSigningKey:
    publicSigningKey:
  authentication:
    endPoint: "https://login.boclips.com/auth"
